#!/usr/bin/env bash
# BigV-twins one-shot deployment.
#
# Usage:
#   ./deploy.sh --zhihu-db /path/to/zhihu.db
#     [--conda-env bigv-twins]
#     [--mcp-port 8770]
#     [--skip-index] [--skip-personas] [--skip-systemd] [--skip-openclaw]
#     [--force-personas]
#
# Each step is idempotent. Re-run after editing source / config and it does
# the right thing. See README.md §6 for what each step does.

set -euo pipefail

# ---------------------------------------------------------------- defaults

ZHIHU_DB=""
CONDA_ENV="bigv-twins"
MCP_PORT="8770"
SKIP_INDEX="false"
SKIP_PERSONAS="false"
SKIP_SYSTEMD="false"
SKIP_OPENCLAW="false"
FORCE_PERSONAS="false"

# ---------------------------------------------------------------- arg parse

usage() {
    sed -n '2,12p' "$0" | sed 's/^# \?//'
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --zhihu-db)        ZHIHU_DB="$2"; shift 2 ;;
        --conda-env)       CONDA_ENV="$2"; shift 2 ;;
        --mcp-port)        MCP_PORT="$2"; shift 2 ;;
        --skip-index)      SKIP_INDEX="true"; shift ;;
        --skip-personas)   SKIP_PERSONAS="true"; shift ;;
        --skip-systemd)    SKIP_SYSTEMD="true"; shift ;;
        --skip-openclaw)   SKIP_OPENCLAW="true"; shift ;;
        --force-personas)  FORCE_PERSONAS="true"; shift ;;
        -h|--help)         usage 0 ;;
        *) echo "unknown arg: $1" >&2; usage 1 ;;
    esac
done

# ---------------------------------------------------------------- paths

PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJ_DIR"

# Locate openclaw binary (PATH first, then nvm-style fallback).
find_openclaw() {
    if command -v openclaw >/dev/null 2>&1; then
        command -v openclaw
        return
    fi
    for f in /home/dtl/.nvm/versions/node/*/bin/openclaw \
             /root/.nvm/versions/node/*/bin/openclaw \
             /usr/local/bin/openclaw; do
        [[ -x "$f" ]] && { echo "$f"; return; }
    done
    return 1
}

OPENCLAW_BIN="$(find_openclaw 2>/dev/null || true)"

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; }

# ---------------------------------------------------------------- step 1

check_prereqs() {
    log "[1/11] checking prerequisites"

    if ! command -v conda >/dev/null 2>&1; then
        err "conda not found on PATH. Install miniconda first: https://docs.conda.io"
        exit 1
    fi
    echo "  conda: $(command -v conda)"

    if [[ -z "$ZHIHU_DB" ]]; then
        err "--zhihu-db is required (path to your zhihu archive sqlite db)"
        usage 1
    fi
    if [[ ! -r "$ZHIHU_DB" ]]; then
        err "zhihu db not readable: $ZHIHU_DB"
        exit 1
    fi
    echo "  zhihu-db: $ZHIHU_DB ($(du -h "$ZHIHU_DB" | cut -f1))"

    if [[ -n "$OPENCLAW_BIN" ]]; then
        echo "  openclaw: $OPENCLAW_BIN"
    else
        warn "openclaw not found — will skip openclaw integration steps."
        SKIP_OPENCLAW="true"
        SKIP_PERSONAS="true"
    fi

    if ! command -v systemctl >/dev/null 2>&1; then
        warn "systemd not found — will skip systemd install."
        SKIP_SYSTEMD="true"
    fi
}

# ---------------------------------------------------------------- step 2

ensure_conda_env() {
    log "[2/11] ensure conda env: $CONDA_ENV"

    # shellcheck source=/dev/null
    source "$(conda info --base)/etc/profile.d/conda.sh"

    if conda env list | awk '{print $1}' | grep -qx "$CONDA_ENV"; then
        echo "  env $CONDA_ENV already exists, skip create"
    else
        echo "  creating env $CONDA_ENV (python=3.12)..."
        conda create -y -n "$CONDA_ENV" python=3.12 >/dev/null
    fi
    conda activate "$CONDA_ENV"
    echo "  active python: $(which python) ($(python --version))"
}

# ---------------------------------------------------------------- step 3

install_package() {
    log "[3/11] pip install -e ."
    pip install -e . 2>&1 | tail -2
    python -c "import bigv_twins, mcp, sentence_transformers, sqlite_vec; print('  imports ok')"
}

# ---------------------------------------------------------------- step 4

generate_env_file() {
    log "[4/11] generating .env"

    if [[ -f .env ]]; then
        echo "  .env exists, backing up to .env.bak"
        cp .env .env.bak
    fi

    cat > .env <<EOF
# Generated by deploy.sh on $(date -Iseconds)

ZHIHU_DB_PATH=$ZHIHU_DB
TWINS_DIR=$PROJ_DIR/twins
PERSONAS_DIR=$PROJ_DIR/personas

EMBEDDING_MODEL=BAAI/bge-base-zh-v1.5
EMBEDDING_DIM=768

CHUNK_SIZE=600
CHUNK_OVERLAP=80

MCP_HOST=127.0.0.1
MCP_PORT=$MCP_PORT

# China-friendly Hugging Face mirror
HF_ENDPOINT=https://hf-mirror.com

# Only needed for one-shot persona generation if openclaw is unavailable.
ANTHROPIC_API_KEY=
EOF
    echo "  wrote .env"
}

# ---------------------------------------------------------------- step 5

pre_download_model() {
    log "[5/11] pre-download embedding model (BGE-base-zh-v1.5)"

    python - <<'PY'
from sentence_transformers import SentenceTransformer
m = SentenceTransformer('BAAI/bge-base-zh-v1.5', device='cpu')
print(f"  model loaded, dim={m.get_sentence_embedding_dimension()}")
PY
}

# ---------------------------------------------------------------- step 6

bootstrap_index() {
    if [[ "$SKIP_INDEX" == "true" ]]; then
        log "[6/11] skip bootstrap index (--skip-index)"
        return
    fi
    log "[6/11] bootstrap index (incremental — re-runs safe)"
    echo "  this can take hours for large bloggers (shen ~5h). Press Ctrl-C to abort;"
    echo "  resume with: python -m bigv_twins.index"
    echo ""
    python -m bigv_twins.index 2>&1 | tail -10
}

# ---------------------------------------------------------------- step 7

generate_personas() {
    if [[ "$SKIP_PERSONAS" == "true" ]]; then
        log "[7/11] skip persona generation (--skip-personas or openclaw missing)"
        return
    fi

    log "[7/11] generate personas via OpenClaw-configured provider"

    local force_flag=""
    if [[ "$FORCE_PERSONAS" == "true" ]]; then
        force_flag="--force"
    fi

    if ! python scripts/generate_personas.py $force_flag 2>&1 | tee /tmp/.gen-personas.log | tail -10; then
        warn "persona generation failed; see /tmp/.gen-personas.log"
        warn "you can retry later with: python scripts/generate_personas.py"
    fi
}

# ---------------------------------------------------------------- step 8

install_systemd() {
    if [[ "$SKIP_SYSTEMD" == "true" ]]; then
        log "[8/11] skip systemd install (--skip-systemd)"
        return
    fi

    log "[8/11] install systemd user units"

    # Patch unit files to use this project's paths + python.
    local py_bin
    py_bin="$(conda info --base)/envs/$CONDA_ENV/bin/python"
    local unit_dir="$HOME/.config/systemd/user"
    mkdir -p "$unit_dir"
    mkdir -p "$PROJ_DIR/logs"

    for unit in bigv-twins-server.service bigv-twins-daily.service bigv-twins-daily.timer; do
        sed -e "s|/home/dtl/projects/BigV-twins|$PROJ_DIR|g" \
            -e "s|/home/dtl/miniconda3/envs/bigv-twins/bin/python|$py_bin|g" \
            "systemd/$unit" > "$unit_dir/$unit"
        echo "  installed $unit"
    done

    echo "  enabling linger so user units survive logout/reboot"
    if sudo -n loginctl enable-linger "$USER" 2>/dev/null; then
        :
    else
        warn "passwordless sudo not available — linger NOT enabled."
        warn "Run manually:  sudo loginctl enable-linger $USER"
    fi

    systemctl --user daemon-reload
    systemctl --user enable --now bigv-twins-server.service
    systemctl --user enable --now bigv-twins-daily.timer

    sleep 3
    echo
    systemctl --user status bigv-twins-server.service --no-pager | head -5 || true
    echo
    systemctl --user list-timers --all --no-pager | grep -E "(NEXT|bigv)" || true
}

# ---------------------------------------------------------------- step 9

register_mcp() {
    if [[ "$SKIP_OPENCLAW" == "true" ]]; then
        log "[9/11] skip openclaw mcp registration (--skip-openclaw or openclaw missing)"
        return
    fi

    log "[9/11] register MCP server with openclaw"
    "$OPENCLAW_BIN" mcp set bigv-twins \
        "{\"url\":\"http://127.0.0.1:$MCP_PORT/mcp\",\"transport\":\"streamable-http\"}" >/dev/null
    echo "  registered. openclaw mcp list:"
    "$OPENCLAW_BIN" mcp list 2>&1 | grep -E "(^-|bigv-twins)" | head -5
}

# ---------------------------------------------------------------- step 10

install_skills() {
    if [[ "$SKIP_OPENCLAW" == "true" ]]; then
        log "[10/11] skip skills copy (--skip-openclaw or openclaw missing)"
        return
    fi

    log "[10/11] copy skills to openclaw workspace"
    local workspace_skills="$HOME/.openclaw/workspace/skills"
    mkdir -p "$workspace_skills"

    for d in skills/bigv-*/; do
        [[ -d "$d" ]] || continue
        local name
        name="$(basename "$d")"
        rm -rf "$workspace_skills/$name"
        cp -r "$d" "$workspace_skills/"
        echo "  copied $name"
    done

    echo "  openclaw skills list | grep bigv:"
    "$OPENCLAW_BIN" skills list 2>&1 | grep -E "bigv-" | head -10 || true
}

# ---------------------------------------------------------------- step 11

smoke_test() {
    log "[11/11] smoke test MCP server"
    if ! ss -tln 2>/dev/null | grep -q ":$MCP_PORT "; then
        warn "port $MCP_PORT not listening; smoke test will likely fail"
    fi
    python scripts/test_mcp_client.py 2>&1 | tail -25 || warn "smoke test reported errors"
}

# ---------------------------------------------------------------- main

main() {
    echo "BigV-twins deploy — $(date)"
    echo "  project dir: $PROJ_DIR"
    echo "  zhihu db:    $ZHIHU_DB"
    echo "  conda env:   $CONDA_ENV"
    echo "  mcp port:    $MCP_PORT"
    echo "  skip-index: $SKIP_INDEX  skip-personas: $SKIP_PERSONAS  skip-systemd: $SKIP_SYSTEMD  skip-openclaw: $SKIP_OPENCLAW"

    check_prereqs
    ensure_conda_env
    install_package
    generate_env_file
    pre_download_model
    bootstrap_index
    generate_personas
    install_systemd
    register_mcp
    install_skills
    smoke_test

    log "DONE."
    echo
    echo "Try it:"
    echo "  $OPENCLAW_BIN agent --agent main -m \"MR Dang 怎么看 A 股市场？\""
    echo
    echo "Useful commands:"
    echo "  systemctl --user status bigv-twins-server"
    echo "  systemctl --user list-timers | grep bigv"
    echo "  journalctl --user -u bigv-twins-server -f"
    echo "  python -m bigv_twins.search --blogger eyu --query 'XX'"
}

main "$@"
